### ISSUE TITLE
Match size

### ISSUE THREAD

**Issue by LeonB** [paluh/ansible-augeas#1]
Can I do something like this?

``` yml
- name: make openssh accept GIT_ ENV variables
  action: augeas command=set path=/files/etc/ssh/sshd_config/AcceptEnv/01 value=GIT_*
  when: augeas command=match path=/files/etc/sshd_config/AcceptEnv/*[.="GIT_*"] size == 0
```

At the moment I get this error: error while evaluating conditional: augeas command=match path=/files/etc/sshd_config/AcceptEnv/_[.="GIT__"] size == 0
