### ISSUE TITLE
inserting new directive... duplicated entry?

### ISSUE THREAD

**Issue by drzraf** [paluh/ansible-augeas#30]
I attempt to add ServerLimit to Apache configuration.
```yaml
- action: augeas
  args:
    commands: |
      ins directive after /files/etc/apache2/mods-available/mpm_event.conf/IfModule[arg=\"mpm_event_module\"]/*[self::directive=\"ThreadLimit\"]
      set /files/etc/apache2/mods-available/mpm_event.conf/IfModule[arg=\"mpm_event_module\"]/directive[.=\"\"] ServerLimit
      set /files/etc/apache2/mods-available/mpm_event.conf/IfModule[arg=\"mpm_event_module\"]/directive[.=\"ServerLimit\"]/arg 32
```

Before:
```
<IfModule mpm_event_module>
	StartServers			 2
	MinSpareThreads		 25
	MaxSpareThreads		 75
	ThreadLimit			 64
	ThreadsPerChild		 25
	MaxRequestWorkers	  150
	MaxConnectionsPerChild   0
</IfModule>
```

After (aside from the lost of indentation, notice the duplicated and empty `ServerLimit` directive):
```
<IfModule mpm_event_module>
	StartServers			 2
	MinSpareThreads		 25
	MaxSpareThreads		 75
	ThreadLimit			 64
	ServerLimit
	ServerLimit	  32
	ThreadsPerChild   25
MaxRequestWorkers 150
MaxConnectionsPerChild 0
</IfModule>
```

Expected:
```
<IfModule mpm_event_module>
	StartServers			 2
	MinSpareThreads		 25
	MaxSpareThreads		 75
	ThreadLimit			 64
	ServerLimit			 32
	ThreadsPerChild		 25
	MaxRequestWorkers	  150
	MaxConnectionsPerChild   0
</IfModule>
```

**Comment by paluh** [comment]
Sorry, I'm nearly offline on holiday till next Sunday, so I will review the issue then.

**Comment by paluh** [comment]
@drzraf Have you tested the same scenario with `augtool`? Does it work as you expect?

**Comment by drzraf** [comment]
Inspired by https://stackoverflow.com/questions/18428930/, I got it to work using this:

```yaml
- action: augeas
  args:
    commands: |
      set /files/etc/apache2/mods-available/mpm_event.conf/IfModule[arg=\"mpm_event_module\"]/directive[.=\"ServerLimit\"] ServerLimit
      set /files/etc/apache2/mods-available/mpm_event.conf/IfModule[arg=\"mpm_event_module\"]/directive[.=\"ServerLimit\"]/arg 42
```

But notice the escaping *even* though it's within a YAML EOF.
If you don't escape it would create a new `<IfModule>` block like the following:
```
<IfModule>
ServerLimit
</IfModule>
<IfModule>
<directive 32>
</directive>
</IfModule>
```
